### ISSUE TITLE
Cards of the Same Type but different values being dealed equally

### ISSUE THREAD

**Issue by tootyta** [Solero/Houdini#10]
Whenever two cards of the same type, say a yellow snow card with a value of 7 and a maybe another card that's yellow/snow but it's value is 2, those two cards will be dealed as if they are the same exact cards and will not count as a move which is incorrect.

**Comment by tootyta** [comment]
This issue is inconsistent and will not always appear after I have tested various times, 
![image](https://user-images.githubusercontent.com/17104414/35711482-b574f2ba-0782-11e8-84f5-b0a427ed8509.png) but here's what the console looked like when it did occur.

**Comment by valid22** [comment]
explain more? That console o/p doesn't support your theory.
