### ISSUE TITLE
Passwords?

### ISSUE THREAD

**Issue by TheOnlyOneLeft** [Solero/Houdini#11]
Hey I was wondering what the passwords are encrypted with and what string I can use to generate different passwords?

**Comment by twizzler** [comment]
Passwords are hashed in bcrypt.
See reference here https://solero.github.io/password

**Comment by ketnipz** [comment]
Please note the information documented on the Wiki is for the AS2 protocol only, however the AS3 protocol differs in only one minor way, that being the static key appended before the final bcrypt hash.
`Y(02.>\'H}t":E1`
Becomes 
`a1ebe00441f5aecb185d0ec178ca2305Y(02.>'H}t\":E1_root`

In future we'll have a dependency that allows AS2 hashes to be used with the AS3 client.

**Comment by TheOnlyOneLeft** [comment]
Thanks for the replies guys  ^-^
