### ISSUE TITLE
Database dump import error

### ISSUE THREAD

**Issue by jeffw16** [Solero/Houdini#12]
Getting an issue with importing `houdini.sql` into my database. I get the error `ERROR 1067 (42000) at line 48: Invalid default value for 'Issued'`.

MySQL version info from `mysql -V`:
`mysql  Ver 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3`

Perhaps it is an issue with `current_timestamp()`, however I am not very familiar with MySQL, so please advise.

**Comment by ketnipz** [comment]
Hi,
Your version of MySQL doesn't support `current_timestamp()` as a default field value. Please update your mysql version.

Please see [here](https://askubuntu.com/questions/750498/mysql-5-5-update-to-mysql-5-7), looks like a recent method for updating a debian machine.

**Comment by jeffw16** [comment]
Ah okay, thanks for the speedy reply!

In that case, I would suggest adding a MySQL version requirement in the README.

Appreciate the help!
