### ISSUE TITLE
CJ Fire Sensei Battle

### ISSUE THREAD

**Issue by miningslayer18** [Solero/Houdini#13]
The Sensei Battle in Card Jitsu Fire does not work.

**Comment by Zaseth** [comment]
You should include some description of your issue. Add some logs for example

**Comment by miningslayer18** [comment]
1: I've already confirmed with a dev that this feature is not yet implemented
2: Simple as when you try to battle Sensei, it goes to the Game, but there is a countdown infinite load. The X button does not work, so you have to relog.

**Comment by Zaseth** [comment]
Provide some logs of when you join the game.

**Comment by miningslayer18** [comment]
Nah, I really don't see a point, considering this feature isn't even implemented yet, so it makes sense that it doesn't work. Cya Zazeth the "Expert"

**Comment by Zaseth** [comment]
Hideous behavior.
