### ISSUE TITLE
redemption animation not plays

### ISSUE THREAD

**Issue by ottovonpeg** [solero/houdini#26]
when you enter redemption code. animation won't show up and you'll get items. it's a server-side problem.

**Comment by ketnipz** [comment]
Could you please confirm which client you saw this on. And what type of code were you redeeming?

**Comment by ottovonpeg** [comment]
> Could you please confirm which client you saw this on. And what type of code were you redeeming?

I am using Vanilla media. I am trying to redeem a few items.

**Comment by ketnipz** [comment]
> I am using Vanilla media. I am trying to redeem a few items.

I am unable to replicate your issue. I redeem items on vanilla client and the "animation" of the box opening appears just fine.

Perhaps you could elaborate on this issue? What made you so sure it was server-side?

**Comment by ottovonpeg** [comment]
It was a server-side problem because you can write anything on "Code Type" however the default value is "BLANKET" and if you write another code type obviously animation won't appear
