### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by cxmatt** [solero/houdini#31]
Hello, I was wondering if their was a list of bugs that are needed to be fixed within using wand as the setup. 

"Snack Shack" stamp is broken.
"Switchbox 3000" stamp is broken.
"Food Fight" stamp is broken. When you throw a snowball outside of mine and school, it is supposed to turn to food, and you get a stamp for that.
There is no Recycling Plant on as2. (Should be added for the stamp.)
"Full House" stamp is broken.
You cannot beat Sensei even with a black belt.
There are no crabs or sharks in Ice Fishing.
"Graduate" stamp is broken. (Finish the surf lesson.)
"Food Fiasco" stamp is broken.
When you complete missions, the medals are supposed to be in your stamp book. I finished 2 medals and didn't get the stamps for each mission. (No, not the earn 50 epf medals stamps, but the medals per mission themself.)
Game day stamps are untenable. I thought it'd be a good idea to have a Game Day party in the future, where you choose a team to be on (Red, yellow, green, blue) get a background and items for that team, (already exist) and you can earn Game Day stamps for completing daily tasks.

These are some a member that uses wand sent me. 

Thanks - Matt.

**Comment by JointKush** [comment]
Stamps for Switchbox 3000, Snack Shack, and Food Fight are client sided. You might have to get the correct versions of those rooms in order for those stamps to work it has nothing to do with Houdini whatsoever.

**Comment by cxmatt** [comment]
Thanks. If i find anymore bugs that aren't server sided can i post them here for you to look into. 

- Matt.

**Comment by JointKush** [comment]
If that's what you wanna do but I think it's best if you join the discord https://discord.com/invite/UPnWKfh

**Comment by cxmatt** [comment]
Okay, I'll post it there thank you. 

My discord: CxMatt#6327

- Matt.

**Comment by ketnipz** [comment]
>"Snack Shack" stamp is broken.
>"Switchbox 3000" stamp is broken.
>"Food Fight" stamp is broken.
>"Food Fiasco" stamp is broken.

Client-side, needs more research.

>"Full House" stamp is broken.

Could be server-side, open a separate issue for this.

>There is no Recycling Plant on as2. 

It's up to you to add the recycling plant back yourself. It's just a swap of room SWF.

>You cannot beat Sensei even with a black belt.

Has very recently been patched. Please make sure you're using an up-to-date repository.

>There are no crabs or sharks in Ice Fishing.

Also recently patched, but not for wand. This prompted me to fast-forward wands media sub-modules, so should be fixed now.

>"Graduate" stamp is broken. (Finish the surf lesson.)

Was not able to replicate, I can earn this stamp just fine. Make sure you actually complete all the lesson tasks!

>I didn't get the stamps for each mission.

Recently patched. Again pull for recent changes.

>Game day stamps are untenable.

Yep. We should just remove these from both media servers...

>If i find anymore bugs that aren't server sided can i post them here for you to look into.

No, please don't do that here. We have [repositories specifically for bug squashing the clients](https://git.solero.me). If you are unsure whether a bug is client sided or not, ask in the [Discord](https://solero.me/discord) first.

Also, please don't open issues and list out bugs like this, it may seem more efficient, but it makes looking back over solved issues more difficult in future. _Open one issue for every bug you find_.
