### ISSUE TITLE
Logging In

### ISSUE THREAD

**Issue by GrizzyWasProgrammed** [solero/houdini#45]
When logging in you have to make your penguin name 

"basil" and can't login with "Basil" same for other penguin names.

Don't know if this is an error on my end or an error within the Houdini source.

**Comment by ketnipz** [comment]
I am unable to replicate this. I can login with any username in any case.

Anything weird about your setup? Custom client files, houdini plugins etc.

**Comment by GrizzyWasProgrammed** [comment]
Using default wand but for other user's it works fine just doesn't for me so that's why i was wondering if this was a error within the source. 

Thanks. 

PS: I was wondering how to remove the map icon's it's within the database right?

**Comment by ketnipz** [comment]
Not sure why this would be an issue for you and nobody else. Maybe put the login server in debug mode and send the terminal output?

Using `--logging-level DEBUG`

**Comment by GrizzyWasProgrammed** [comment]
I made a new penguin and it seemed to fix the issue i think it might have been the penguin's name within the database. 

Thanks for the support.
