### ISSUE TITLE
Issue: Bug report

### ISSUE THREAD

**Issue by EmperorBale** [solero/houdini#48]
**Describe the bug**
wow new template

**Client Type:**
Vanilla and/or Legacy
both
**To Reproduce**

**Install Method**
Wand/Manual setup/Other (please specify)

**Expected behavior**

**Screenshots**
If this is a bug that happens in-game, post a screenshot with dev-tools open in your browser (F12 to open).

**Server Info:**
 - OS: [e.g. Windows/Linux/macOS]

**Additional context**

**Comment by Connor800** [comment]
Leave a comment
