### ISSUE TITLE
when registering a new penguin does not enter the igloo.

### ISSUE THREAD

**Issue by geometry88** [solero/houdini#51]
when registering a new penguin does not enter the igloo.

no entry is added to table penguin_igloo_room and in penguin row igloo = NULL

rolling back to the old version of the houdini helped me

**Comment by leolmds** [comment]
Same problem here :/  what version of houdini can you use to solve?

**Comment by geometry88** [comment]
> Same problem here :/ what version of houdini can you use to solve?

https://github.com/solero/houdini/tree/a3bf192ec0dd41c13d4f96263dc66cebec03d304

**Comment by leolmds** [comment]
> https://github.com/solero/houdini/tree/a3bf192ec0dd41c13d4f96263dc66cebec03d304

TYYYY <3 *-* SOLVED !

**Comment by ketnipz** [comment]
Fixed in commit https://github.com/solero/houdini/commit/da69239f49d77952058d555687a8a45dffd04e5b
