### ISSUE TITLE
Smoothie Smash mental breakdown

### ISSUE THREAD

**Issue by DiamondFiire** [solero/houdini#59]
**Describe the bug**
On leh AS3, Once you pass 20 minutes in Smoothie Smash, the timer start's having a mental break down.
**Expected behavior**
Could be a client issue? But honestly don't know lol
![Screenshot_5448](https://user-images.githubusercontent.com/27214958/90960469-a229d080-e499-11ea-859b-0df429828f63.png)

**Comment by ketnipz** [comment]
This bug is most certainly client related and so we can't fix it from this repository.

Side note: 20 minutes... 20 minutes?!!! In smoothie smash? How!!!

**Comment by DiamondFiire** [comment]
> This bug is most certainly client related and so we can't fix it from this repository.
> 
> Side note: 20 minutes... 20 minutes?!!! In smoothie smash? How!!!

Total Skill!
