### ISSUE TITLE
I keep getting an error

### ISSUE THREAD

**Issue by Sup-Sup123** [solero/houdini#65]
So, I keep getting an error that says "aioredis" is not supported for this version of python, could someone help?

**Comment by Connor800** [comment]
Crazy assumption but it may be possible aioredis is not supported in your Python version

**Comment by Sup-Sup123** [comment]
Yeah, but I don't know what version is supported

**Comment by pent-est** [comment]
> Yeah, but I don't know what version is supported
Supports 3.5.3+ so check your python version

**Comment by Sup-Sup123** [comment]
It's version 3.9.0

**Comment by Sup-Sup123** [comment]
"aioredis doesn't support Python version prior 3.5"

**Comment by NathOnagal** [comment]
> "aioredis doesn't support Python version prior 3.5"

There you have the answer

**Comment by ClubPenguiin** [comment]
hi

**Comment by ketnipz** [comment]
Not an issue with Houdini. Consult pip docs or our Discord.
