### ISSUE TITLE
The Remote Computer Refused The Connection: WinError1225

### ISSUE THREAD

**Issue by jbsec** [solero/houdini#68]
Installs went fine, disabled firewall and reset most network settings, still with the error. Just wondering if there is a fix, this was in reponse to the "python bootstrap.py login" command.

**Comment by zombiestruck** [comment]
Did you use wand?

**Comment by jbsec** [comment]
The command does not include that? What did you run exactly?

**Comment by zombiestruck** [comment]
https://github.com/solero/wand

**Comment by AllinolCP** [comment]
this usually means either you didn't install postgres or redis
