### ISSUE TITLE
Capes do not properly render on AS2 playercard

### ISSUE THREAD

**Issue by Taker653** [solero/houdini#70]
**Describe the bug**
When equipping one of the capes, only the top portion of the cape shows on the playercard whereas the bottom part does not render.

**Client Type:**
Legacy only, properly renders on the vanilla client

**To Reproduce**
Equip a cape (red cape, blue cape, etc.)
Open your playercard

**Install Method**
Wand

**Expected behavior**
The cape should also appear on the bottom towards the penguin's feet

**Screenshots**
How it appears on AS2
![image](https://user-images.githubusercontent.com/18584509/116928536-38b6b000-ac2b-11eb-8f76-63715ece5d2f.png)

How it appears on AS3
![image](https://user-images.githubusercontent.com/18584509/116928958-bf6b8d00-ac2b-11eb-817c-a73484fa9084.png)

**Server Info:**
 Linux

**Comment by floogal** [comment]
This is most likely a client side bug, and this issue should not be opened on this repo.

**Comment by AllinolCP** [comment]
This is a client issue so you should be opening the issue on https://git.solero.me/solero/legacy-media
